### PR TITLE
Remove version check

### LINKED ISSUE #18: Allow for prefixed tags
When using [cargo release](https://github.com/sunng87/cargo-release) with a Rust workspace (i.e one containing multiple projects) the tags are created as `[proj-name]-[version]`. For example: `gping-v1.2.3`.

This unfortunately causes this action to not work ([see here](https://github.com/orf/gping/runs/3108981656?check_suite_focus=true)), as it says `Skipping: the formula version 'v1.2.1' is newer than 'gping-v1.2.3'`.

Is there a way around this? Perhaps by supplying some kind of regex to extract the version and ignore the prefix?

### PR DESCRIPTION
**Pull request by stefreak**
This fixes #18: Now bump-homebrew-formula-action will not assume anything about the version format, and simply create a Pull request or a new commit if something has changed.

The action will still skip creating the PR if nothing has changed.

One more example why this might be helpful: Let's say the maintainer only wants to change the URL, but keep the version as-is. With the version check in place this wasn't possible.

### CODE REVIEW

**Comment by mislav** [comment]
Thanks for the improvement, but the version check was introduced to disallow version downgrades:
1. Project publishes latest version `v1.2.3` but also backports a fix to `v1.1.2`;
2. The `v1.1.2` release job is processed last;
3. The job downgrades the version number in the Homebrew formula and sends that as a PR to Homebrew-core.

Can there be a compromise between your solution and some mechanism that guards against downgrades?

**Comment by stefreak** [comment]
@mislav Maybe we could add a way to guard against downgrades in the example workflow in the readme?

One way that comes to my mind is to look into all the existing tags in another step, and see wether it is the latest one. 

If we move this logic out into the workflow itself, everyone can customize it to their needs.

Of course it would be a breaking change and would need to be communicated in the release notes.

What do you think about that approach?

**Comment by stefreak** [comment]
@mislav Hello, which option do you prefer? I might be able to find the time to finish this PR if you think it is worth it.

**Comment by mislav** [comment]
Sorry for the late reply!

I would be in favor of an option that improves extracting versions from the archive name, and if it wasn't able to detect something that looks like a version or like `someprefix-v{VERSION}`, it turns off version upgrade check. I think that would be best of both worlds.

**Comment by stefreak** [comment]
We went for using the peter-evans/create-pull-request action now (https://github.com/garden-io/garden/blob/main/.github/workflows/reusable-create-homebrew-pr.yml) – it suits our needs a little better. But thank you still for maintaining this action 👍

**Pull request closed without merging**
